.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ALCHEMIST 1 "November 22, 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
alchemist \- Rolemaster Standard System (RMSS) and Rolemaster Fantasy Roleplay
(RMFRP) object editor. This is part of the
.B Nebula
suite.
.SH SYNOPSIS
.B alchemist
.SH DESCRIPTION

.I Alchemist
is a GNOME2 program to create, edit and maintain special objects for use with
.B Nebula
, the RMSS/RMFRP Character Generator; though it can be used with other 
editors that understand the XML DTD of the object files.

.br

Data is stored in a publically available XML format. For more information on
the format see 
.B http://nash.nu/Rolemaster/XML/
\.

.SH AUTHOR
The authors of Alchemist are Sylvain Glaize 
and Brett Nash <brettn@cse.unsw.edu.au>.
This manual page was written by Roberto Suarez Soto <turgon@debian.org>,
for the Debian GNU/Linux system (but may be used by others).

.SH COPYRIGHT

Rolemaster, Rolemaster Standard System (RMSS) and Rolemaster Fantasy
Roleplaying are property of Iron Crown Enterprises.
